//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public string ID { get; set; }
        public string SupplierCode { get; set; }
        public string TypeID { get; set; }
        public string MaterialID { get; set; }
        public string SizeID { get; set; }
        public string FinishingID { get; set; }
        public string AdditionalID { get; set; }
        public string ShapeID { get; set; }
        public string Description { get; set; }
        public Nullable<double> SizeL { get; set; }
        public Nullable<double> SizeW { get; set; }
        public Nullable<double> SizeD { get; set; }
        public Nullable<double> BoxSizeL { get; set; }
        public Nullable<double> BoxSizeW { get; set; }
        public Nullable<double> BoxSizeD { get; set; }
        public Nullable<double> GrossWeight { get; set; }
        public Nullable<double> NetWeight { get; set; }
        public string ImgUrl { get; set; }
        public string QRCode { get; set; }
        public Nullable<decimal> PriceSupplier { get; set; }
        public Nullable<decimal> PriceSales { get; set; }
        public string Currency { get; set; }
    
        public virtual Additional Additional { get; set; }
        public virtual Finishing Finishing { get; set; }
        public virtual Material Material { get; set; }
        public virtual Shape Shape { get; set; }
        public virtual Size Size { get; set; }
        public virtual Type Type { get; set; }
    }
}
