//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string OrderID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string SupplierID { get; set; }
    
        public virtual Order Orders1 { get; set; }
        public virtual Order Order1 { get; set; }
        public virtual Order Orders11 { get; set; }
        public virtual Order Order2 { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
