//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestArticle
    {
        public string ArticleID { get; set; }
        public string ArticleName { get; set; }
    }
}
